name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.issue.number }}
  LEO: ${{ github.event.pull_request }}
  BODY: This issue is available for anyone to work on.

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: See vars
        run: echo "$LEO" -> "$NUMBER" -> "$BODY"
      - name: Add comment
        run: gh pr comment "$NUMBER" --body "$BODY"
