name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.pull_request.number }}
  BODY: This issue is available for anyone to work on.

jobs:
  verify-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Instalar dependências
        run: npm install

      - name: Verificar dependências desatualizadas
        id: check_outdated
        run: |
          npm outdated waves-ui --json > outdated.json

      - name: Checar atualizações
        run: |
          if [ -s outdated.json ]; then
            installed_version=$(node -pe "require('./package.json').dependencies['waves-ui']")
            latest_version=$(npm show waves-ui version)
            echo "$latest_version"
            echo "$installed_version"

            run: gh pr comment "$NUMBER" --body Versão atual "$installed_version" você pode atualizar para -> "$latest_version"
          else
            echo "Não há atualizações disponíveis."
          fi
