name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  GH_OWNER: ${{ github.repository_owner }}
  NUMBER: ${{ github.event.pull_request.number }}
  BODY: This issue is available for anyone to work on.

jobs:
  verify-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verificar dependências desatualizadas
        id: check_outdated
        run: |
          npm outdated waves-ui --json > outdated.json
      - name: View outdated dependencies
        run: |
          cat outdated.json
      - name: Verificar comentário existente
        id: get_comments
        run: |
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GH_OWNER/$GH_REPO/pulls/comments > comments.txt
      - name: Read comments from file
        id: read_comments
        run: |
          COMMENTS=$(<comments.txt)
      - name: Use comments
        run: |
          echo "Comments: $COMMENTS"
      - name: Checar atualizações
        run: |
          if [ -s outdated.json ]; then
            latest_version=$(npm show waves-ui version)
            installed_version=$(node -pe "require('./package.json').dependencies['waves-ui'].replace('^', '')")

            COMMENT="#$NUMBER.
            Atualização Disponível

            Existe uma atualização na biblioteca Waves-ui.

            Versão instalada: $installed_version
            Nova Versão: $latest_version

            Por favor, verifique as notas de lançamento e atualize sua dependência para aproveitar as correções de bugs e novos recursos."
            

            # response=$(curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/$GH_OWNER/$GH_REPO/issues/$NUMBER/comments")
            response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GH_OWNER/$GH_REPO/issues/comments)
            echo "aqui $response"

            if [[ "$response" == *"#$NUMBER."* ]]; then
              echo "O comentário $COMMENT já existe no PR #$NUMBER."
            else
              gh pr comment "$NUMBER" --body "$COMMENT"
            fi 
          else
            echo "Não há atualizações disponíveis."
          fi
