name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: ${{ github.event.pull_request.number }}
  BODY: This issue is available for anyone to work on.

jobs:
  verify-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Verificar se a biblioteca está desatualizada
        run: |
          outdated_check=$(npm outdated waves-ui)
          echo aqui "$outdated_check"
          # if [ "$outdated_check" ]; then
          #     echo A sua biblioteca está desatualizada.
          #     gh pr comment "$NUMBER" --body "$BODY"
          # fi
