name: 'Verify PR'

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  GH_OWNER: ${{ github.repository_owner }}
  NUMBER: ${{ github.event.pull_request.number }}
  BODY: This issue is available for anyone to work on.

jobs:
  verify-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verificar dependências desatualizadas
        id: check_outdated
        run: |
          npm outdated waves-ui --json > outdated.json
      - name: Verificar comentarios existentes
        id: get_comment
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <$GH_TOKEN>" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GH_OWNER/$GH_REPO/pulls/$NUMBER/comments > comments.json
            ls -l
      - name: Checar atualizações
        run: |
          if [ -s outdated.json ]; then
            latest_version=$(npm show waves-ui version)
            installed_version=$(node -pe "require('./package.json').dependencies['waves-ui'].replace('^', '')")
            COMMENT="#$NUMBER. Atualização Disponível
            
            Existe uma atualização na biblioteca Waves-ui.
            Versão instalada: $installed_version
            Nova Versão: $latest_version

            Por favor, verifique as notas de lançamento e atualize sua dependência para aproveitar as correções de bugs e novos recursos."
            
            if [ -s comments.json ]; then
              # gh pr comment "$NUMBER" --body "$COMMENT"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer <$GH_TOKEN>" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$GH_OWNER/$GH_REPO/pulls/$NUMBER/comments \
                -d '{"body":"Great stuff!","commit_id":"6dcb09b5b57875f334f61aebed695e2e4193db5e","path":"file1.txt","start_line":1,"start_side":"RIGHT","line":2,"side":"RIGHT"}'
            else
              echo "O comentário $COMMENT já existe no PR #$NUMBER."
            fi 
          else
            echo "Não há atualizações disponíveis."
          fi
